# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1391db7e0146c94befb15db55edd32ce4ae38332d23bf7f6818514f42ac0ca08a54971051b9a471b9779138c367f2974a77d83e33c6dcd03e10909666ce7d298

test:
  secret_key_base: 55e3fe8684e952574c3c6712c8824642496b325419c3281f1fada1d8fe36b379db962f2964feb4dc46f391df0c51ce94118894e8c337f48be3c7fed9e257ed68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
